### ISSUE TITLE
Error when installing on alpine or slim docker images

### ISSUE THREAD

**Issue by paul** [socketry/io-event#40]
This isn't strictly an issue with `io-event` itself, but I'm not sure where to start investigating. 

When installing this gem in the docker container `ruby:3.1-bullseye`, it works fine. In the `ruby:3.1-alpine` and `ruby:3.1-slim-bullseye` images, however, it fails to build:

```
$ docker run --rm -it ruby:3.1.2-slim-bullseye sh
...
# gem install io-event
Fetching io-event-1.0.9.gem
Building native extensions. This could take a while...
ERROR:  Error installing io-event:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/io-event-1.0.9/ext
/usr/local/bin/ruby -I /usr/local/lib/ruby/3.1.0 -r ./siteconf20221009-2-lecj4o.rb extconf.rb
checking for rb_ext_ractor_safe()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
/usr/local/lib/ruby/3.1.0/mkmf.rb:498:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/local/lib/ruby/3.1.0/mkmf.rb:591:in `try_link0'
	from /usr/local/lib/ruby/3.1.0/mkmf.rb:609:in `try_link'
	from /usr/local/lib/ruby/3.1.0/mkmf.rb:830:in `try_func'
	from /usr/local/lib/ruby/3.1.0/mkmf.rb:1119:in `block in have_func'
	from /usr/local/lib/ruby/3.1.0/mkmf.rb:1007:in `block in checking_for'
	from /usr/local/lib/ruby/3.1.0/mkmf.rb:362:in `block (2 levels) in postpone'
	from /usr/local/lib/ruby/3.1.0/mkmf.rb:332:in `open'
	from /usr/local/lib/ruby/3.1.0/mkmf.rb:362:in `block in postpone'
	from /usr/local/lib/ruby/3.1.0/mkmf.rb:332:in `open'
	from /usr/local/lib/ruby/3.1.0/mkmf.rb:358:in `postpone'
	from /usr/local/lib/ruby/3.1.0/mkmf.rb:1006:in `checking_for'
	from /usr/local/lib/ruby/3.1.0/mkmf.rb:1118:in `have_func'
	from extconf.rb:36:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/bundle/extensions/x86_64-linux/3.1.0/io-event-1.0.9/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/io-event-1.0.9 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/3.1.0/io-event-1.0.9/gem_make.out

# cat /usr/local/bundle/extensions/x86_64-linux/3.1.0/io-event-1.0.9/mkmf.log
LD_LIBRARY_PATH=.:/usr/local/lib "gcc -o conftest -I/usr/local/include/ruby-3.1.0/x86_64-linux -I/usr/local/include/ruby-3.1.0/ruby/backward -I/usr/local/include/ruby-3.1.0 -I.    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable -Wundef  -fPIC -Wall -std=c99 conftest.c  -L. -L/usr/local/lib -Wl,-rpath,/usr/local/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--no-as-needed     -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lruby  -lm  -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */
```

I don't know much about building Ruby, Is `rb_ext_ractor_safe` really the issue, or is something else missing needed to compile gems? Or is it a dependency I can install later so this gem will compile?

**Comment by paul** [comment]
Turns out its not just io-event, its any compiled gem, because alpine is missing a compiler at all. Here's what it took to install the gem, in case anyone else comes across this:

`RUN apk add --update gcc make libc-dev`

**Comment by ioquatix** [comment]
I have also done this before and wondered wtf is going wrong with my environment only to realise it's missing a compiler.
