### ISSUE TITLE
`io_uring` backend can deadlock infrequently.

### ISSUE THREAD

**Issue by ioquatix** [socketry/io-event#54]
```
samuel@aiko ~/P/s/async-pool ((220df6b8)) [1]> sus
/home/samuel/.gem/ruby/3.2.1/gems/sus-0.20.3/lib/sus/output/text.rb:93:in `write': deadlock; lock already owned by another fiber belonging to the same thread (ThreadError)
	from /home/samuel/.gem/ruby/3.2.1/gems/sus-0.20.3/lib/sus/output/text.rb:93:in `block in write'
	from /home/samuel/.gem/ruby/3.2.1/gems/sus-0.20.3/lib/sus/output/text.rb:90:in `each'
	from /home/samuel/.gem/ruby/3.2.1/gems/sus-0.20.3/lib/sus/output/text.rb:90:in `write'
	from /home/samuel/.gem/ruby/3.2.1/gems/sus-0.20.3/lib/sus/assertions.rb:106:in `print'
	from /home/samuel/.gem/ruby/3.2.1/gems/sus-0.20.3/lib/sus/config.rb:116:in `print_summary'
	from /home/samuel/.gem/ruby/3.2.1/gems/sus-0.20.3/lib/sus/config.rb:110:in `after_tests'
	from /home/samuel/.gem/ruby/3.2.1/gems/covered-0.20.1/lib/covered/sus.rb:25:in `after_tests'
	from /home/samuel/.gem/ruby/3.2.1/gems/sus-0.20.3/bin/sus:24:in `<top (required)>'
	from /home/samuel/.gem/ruby/3.2.1/bin/sus:25:in `load'
	from /home/samuel/.gem/ruby/3.2.1/bin/sus:25:in `<main>'
```

[gems.locked.txt](https://github.com/socketry/io-event/files/10946722/gems.locked.txt)

It looks like the problem is the write operation is interrupted by an exception and this causes incorrect resumption of the fiber which breaks locking. This is probably pretty hard to test, but should be fixed by wrapping `io_read` and `io_write` in exception handling `rb_rescue` with appropriate clean up.

**Comment by ioquatix** [comment]
```c
static int
io_write(struct IO_Event_Selector_URing *data, VALUE fiber, int descriptor, char *buffer, size_t length)
{
	// The below code is equivalent to:
	// size_t result = write(descriptor, buffer, length);
	// if (result == -1) {
	// 	return -errno;
	// } else {
	// 	return result;
	// }
	
	struct io_write_arguments arguments = {
		.data = data,
		.fiber = fiber,
		.descriptor = descriptor,
		.buffer = buffer,
		.length = length,
	};
	
	int result = RB_NUM2INT(
		rb_rescue(io_write_submit, (VALUE)&arguments, io_write_cancel, (VALUE)&arguments)
	);
	
	if (DEBUG) fprintf(stderr, "io_write:IO_Event_Selector_fiber_transfer -> %d\n", result);
	
	return result;
}
```

Replacing the asynchronous write with the synchronous write fixes the issue, so it points to something being wrong with the asynchronous write.

**Comment by ioquatix** [comment]
Okay, I found the root cause.

During the termination phase of the selector, `Console.logger.warn` is invoked. This causes an asynchronous write, which never completes, and this leaves the IO in a deadlocked state.

**Comment by ioquatix** [comment]
At least one fix for this:

https://github.com/socketry/io-event/commit/6032cb8b71aee9a8b287243652b1845c85b18c4d

**Comment by ioquatix** [comment]
One half of the issue is fixed here, now, the other half needs to be fixed in https://github.com/socketry/async/pull/219
